/*
 * Crop Sentinel AI — Phase 6: Zone tagging + history storage
 * ---------------------------------------------------------------------
 * Scope (per §7 Phase 6): a zone-tag input screen (grid cell, e.g. "B4")
 * shown before each scan, and per-zone scan history stored in a fixed-size
 * in-memory ring buffer with timestamps.
 *
 * Acceptance test this file is built to satisfy: scan the same zone twice
 * and confirm both readings are retrievable and correctly ordered by time.
 * After every successful scan this sketch prints that zone's full stored
 * history to Serial (oldest -> newest) specifically so you can verify that
 * test by eye during the demo/dev loop.
 *
 * This file is Phase 5/6's sketch (TFT/touch bring-up, zone tagging,
 * history, JSON parsing) with the real Phase 4 TinyML model wired in,
 * replacing the earlier mean-threshold stub.
 *
 * ****** Phase 4 model ******
 * tinyModelVerdict() now runs the real fixed-point logistic regression
 * from tiny_model.h (generated by training/train_tiny_model.py). Make
 * sure tiny_model.h in this sketch folder is the one YOUR training run
 * produced, not the all-zero placeholder -- see the comment on that
 * function below.
 *
 * RAM DISCIPLINE (per §4.3): history is a small FIXED-size ring buffer,
 * not a growing list -- see MAX_ZONES / SCANS_PER_ZONE below. These were
 * tightened from (6,4,20) to (3,3,16) specifically to fix a real
 * "data section exceeds available space" compile error -- the original
 * values alone used ~840 bytes of this board's 2KB total RAM. The model
 * weights in tiny_model.h were also moved to PROGMEM (flash) for the same
 * reason, and the JSON reply parser was rewritten to stream field-by-field
 * instead of buffering a ~330+ byte line on the stack. If you hit RAM
 * trouble again, MAX_ZONES/SCANS_PER_ZONE/CLASS_NAME_LEN are still the
 * first things to shrink further.
 *
 * Libraries needed (Library Manager):
 *   - Adafruit GFX Library
 *   - Adafruit ILI9341
 *   - XPT2046_Touchscreen (Paul Stoffregen)
 */

#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_ILI9341.h>
#include <XPT2046_Touchscreen.h>
#include <SoftwareSerial.h>
#include "tiny_model.h"

// ---------------------------------------------------------------------
// Pin map -- unchanged from Phase 5.
// ---------------------------------------------------------------------
#define TFT_CS     10
#define TFT_RESET  9
#define TFT_DC     8

#define TOUCH_CS   7
#define TOUCH_IRQ  6

#define ESP_RX_PIN 2
#define ESP_TX_PIN 3
#define ESP_BAUD   9600

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC, TFT_RESET);
XPT2046_Touchscreen touch(TOUCH_CS, TOUCH_IRQ);
SoftwareSerial espLink(ESP_RX_PIN, ESP_TX_PIN);

#define TS_MINX 200
#define TS_MAXX 3800
#define TS_MINY 200
#define TS_MAXY 3800

// FEAT_LEN must match FEATURE_COUNT on the ESP32 (4x4 grid x 4 stats = 64).
// This replaces the earlier 8-value placeholder used before the real
// Phase 4 feature extractor existed.
#define FEAT_LEN 64
// (No fixed line buffer needed anymore -- see receiveScanResult() below,
// which streams the reply field-by-field instead of buffering a whole line.)

#define COLOR_BG        ILI9341_BLACK
#define COLOR_TEXT      ILI9341_WHITE
#define COLOR_BUTTON    ILI9341_DARKGREEN
#define COLOR_BUTTON_TX ILI9341_WHITE
#define COLOR_HEALTHY   ILI9341_GREEN
#define COLOR_DISEASED  ILI9341_RED
#define COLOR_MUTED     ILI9341_LIGHTGREY
#define COLOR_GRID_CELL ILI9341_NAVY
#define COLOR_GRID_TX   ILI9341_WHITE

#define BTN_X 20
#define BTN_Y 260
#define BTN_W 200
#define BTN_H 50

// ---------------------------------------------------------------------
// Zone grid geometry -- 5 columns (A-E) x 5 rows (1-5) = 25 zones, e.g.
// "B4". Matches the grid-cell tagging style from §6's protocol examples.
// If your field layout wants Row/Plant numbers instead of a letter grid,
// only zoneIdForCell() below needs to change -- everything downstream
// (history, display) just treats zone IDs as opaque short strings.
// ---------------------------------------------------------------------
#define GRID_COLS 5
#define GRID_ROWS 5
#define GRID_X 15
#define GRID_Y 55
#define GRID_CELL 40
#define GRID_GAP 6

// ---------------------------------------------------------------------
// History storage -- fixed-size ring buffer per zone, per the RAM budget
// note in §4.3. Tune these two constants first if you hit RAM trouble.
// ---------------------------------------------------------------------
#define MAX_ZONES        3   // distinct zones remembered at once (oldest zone evicted if full)
#define SCANS_PER_ZONE    3  // ring buffer depth per zone
#define CLASS_NAME_LEN   16  // matches ScanResult.className's size -- no point storing more than that ever holds

struct ScanRecord {
  char classNameTrunc[CLASS_NAME_LEN];
  float confidence;
  unsigned long timestampMs; // millis() since boot -- see note in printZoneHistory()
  bool used;
};

struct ZoneSlot {
  char zoneId[4];             // e.g. "B4\0"
  bool inUse;
  ScanRecord scans[SCANS_PER_ZONE];
  uint8_t nextWriteIndex;     // ring buffer write cursor
  uint8_t count;              // how many of scans[] are actually populated (<= SCANS_PER_ZONE)
};

ZoneSlot zoneHistory[MAX_ZONES];
uint8_t zoneCount = 0; // how many of zoneHistory[] slots are in use

enum AppScreen { SCREEN_IDLE, SCREEN_ZONE_PICK, SCREEN_SCANNING, SCREEN_RESULT };
AppScreen currentScreen = SCREEN_IDLE;

char currentZoneId[4] = "";

struct ScanResult {
  char className[16];
  float confidence;
  int16_t feat[FEAT_LEN];
  bool valid;
};

// =======================================================================
// History storage
// =======================================================================

// Finds an existing zone slot, or creates one if there's room. Returns
// nullptr only if MAX_ZONES is full and zoneId isn't already tracked --
// in that case we just don't store history for this scan rather than
// silently overwriting a different zone's data (see note in addScanToHistory).
ZoneSlot *findOrCreateZone(const char *zoneId) {
  for (uint8_t i = 0; i < zoneCount; i++) {
    if (strcmp(zoneHistory[i].zoneId, zoneId) == 0) {
      return &zoneHistory[i];
    }
  }
  if (zoneCount < MAX_ZONES) {
    ZoneSlot &z = zoneHistory[zoneCount];
    strncpy(z.zoneId, zoneId, sizeof(z.zoneId) - 1);
    z.zoneId[sizeof(z.zoneId) - 1] = '\0';
    z.inUse = true;
    z.nextWriteIndex = 0;
    z.count = 0;
    for (uint8_t s = 0; s < SCANS_PER_ZONE; s++) z.scans[s].used = false;
    zoneCount++;
    return &zoneHistory[zoneCount - 1];
  }
  return nullptr; // MAX_ZONES exhausted and this is a brand-new zone
}

void addScanToHistory(const char *zoneId, const char *className, float confidence) {
  ZoneSlot *z = findOrCreateZone(zoneId);
  if (!z) {
    Serial.println("[WARN] MAX_ZONES reached -- not tracking history for this new zone. Raise MAX_ZONES if you need more concurrent zones.");
    return;
  }

  ScanRecord &rec = z->scans[z->nextWriteIndex];
  strncpy(rec.classNameTrunc, className, CLASS_NAME_LEN - 1);
  rec.classNameTrunc[CLASS_NAME_LEN - 1] = '\0';
  rec.confidence = confidence;
  rec.timestampMs = millis();
  rec.used = true;

  z->nextWriteIndex = (z->nextWriteIndex + 1) % SCANS_PER_ZONE;
  if (z->count < SCANS_PER_ZONE) z->count++;
}

// Prints a zone's history oldest -> newest, purely for demo/dev verification
// of the Phase 6 acceptance test (scan same zone twice, confirm both
// readings retrievable and correctly time-ordered).
//
// NOTE: timestampMs is millis() since the Uno last booted, NOT wall-clock
// time -- there's no RTC in this build. It's still monotonic and correct
// for ordering within a single power-on session, which is all the
// acceptance test asks for. Add an RTC module later if you need real
// wall-clock timestamps across power cycles.
void printZoneHistory(const char *zoneId) {
  ZoneSlot *z = nullptr;
  for (uint8_t i = 0; i < zoneCount; i++) {
    if (strcmp(zoneHistory[i].zoneId, zoneId) == 0) {
      z = &zoneHistory[i];
      break;
    }
  }
  if (!z) {
    Serial.println("[HISTORY] (no history found for this zone)");
    return;
  }

  Serial.print("[HISTORY] Zone ");
  Serial.print(zoneId);
  Serial.print(" -- ");
  Serial.print(z->count);
  Serial.println(" reading(s), oldest first:");

  // Ring buffer readout in chronological order: start at the oldest slot,
  // which is nextWriteIndex when the buffer is full, or 0 when it isn't.
  uint8_t startIdx = (z->count < SCANS_PER_ZONE) ? 0 : z->nextWriteIndex;
  for (uint8_t n = 0; n < z->count; n++) {
    uint8_t idx = (startIdx + n) % SCANS_PER_ZONE;
    ScanRecord &rec = z->scans[idx];
    if (!rec.used) continue;
    Serial.print("  t=");
    Serial.print(rec.timestampMs);
    Serial.print("ms  class=");
    Serial.print(rec.classNameTrunc);
    Serial.print("  confidence=");
    Serial.println(rec.confidence, 2);
  }
}

// Returns the previous (second-most-recent) reading for a zone, if any --
// used to show a quick "up from X%" hint on the result screen ahead of the
// full Phase 7 trend graph. Returns false if there's no prior reading.
bool getPreviousReading(const char *zoneId, ScanRecord &out) {
  for (uint8_t i = 0; i < zoneCount; i++) {
    if (strcmp(zoneHistory[i].zoneId, zoneId) != 0) continue;
    ZoneSlot &z = zoneHistory[i];
    if (z.count < 2) return false; // only the just-added reading exists
    // Most recent is at (nextWriteIndex - 1); previous is one before that.
    int lastIdx = (z.nextWriteIndex + SCANS_PER_ZONE - 1) % SCANS_PER_ZONE;
    int prevIdx = (lastIdx + SCANS_PER_ZONE - 1) % SCANS_PER_ZONE;
    if (!z.scans[prevIdx].used) return false;
    out = z.scans[prevIdx];
    return true;
  }
  return false;
}

// =======================================================================
// UI: zone grid picker
// =======================================================================

void zoneIdForCell(uint8_t col, uint8_t row, char *outBuf) {
  outBuf[0] = 'A' + col;
  outBuf[1] = '1' + row;
  outBuf[2] = '\0';
}

void drawZonePickScreen() {
  tft.fillScreen(COLOR_BG);
  tft.setTextColor(COLOR_TEXT);
  tft.setTextSize(2);
  tft.setCursor(10, 15);
  tft.println("Tag Zone");
  tft.setTextSize(1);
  tft.setTextColor(COLOR_MUTED);
  tft.setCursor(10, 38);
  tft.println("Tap a cell to select and start scanning");
  tft.setTextColor(COLOR_TEXT);

  for (uint8_t row = 0; row < GRID_ROWS; row++) {
    for (uint8_t col = 0; col < GRID_COLS; col++) {
      int x = GRID_X + col * (GRID_CELL + GRID_GAP);
      int y = GRID_Y + row * (GRID_CELL + GRID_GAP);
      tft.fillRoundRect(x, y, GRID_CELL, GRID_CELL, 4, COLOR_GRID_CELL);

      char zoneId[4];
      zoneIdForCell(col, row, zoneId);
      tft.setTextColor(COLOR_GRID_TX);
      tft.setTextSize(1);
      // Rough centering for a 2-char label in a GRID_CELL-wide box.
      tft.setCursor(x + GRID_CELL / 2 - 6, y + GRID_CELL / 2 - 4);
      tft.println(zoneId);
    }
  }
}

// Returns true and fills outZoneId if (x,y) landed on a grid cell.
bool zonePickTouchHit(int16_t x, int16_t y, char *outZoneId) {
  int gridWidth = GRID_COLS * (GRID_CELL + GRID_GAP) - GRID_GAP;
  int gridHeight = GRID_ROWS * (GRID_CELL + GRID_GAP) - GRID_GAP;
  if (x < GRID_X || x > GRID_X + gridWidth || y < GRID_Y || y > GRID_Y + gridHeight) {
    return false;
  }
  int relX = x - GRID_X;
  int relY = y - GRID_Y;
  int col = relX / (GRID_CELL + GRID_GAP);
  int row = relY / (GRID_CELL + GRID_GAP);
  // Reject taps that landed in the gap between cells.
  if (relX % (GRID_CELL + GRID_GAP) > GRID_CELL) return false;
  if (relY % (GRID_CELL + GRID_GAP) > GRID_CELL) return false;
  if (col >= GRID_COLS || row >= GRID_ROWS) return false;

  zoneIdForCell(col, row, outZoneId);
  return true;
}

// =======================================================================
// UI: idle / scanning / result screens (structure carried over from Phase 5)
// =======================================================================

void drawScanButton() {
  tft.fillRoundRect(BTN_X, BTN_Y, BTN_W, BTN_H, 8, COLOR_BUTTON);
  tft.setTextColor(COLOR_BUTTON_TX);
  tft.setTextSize(2);
  tft.setCursor(BTN_X + 30, BTN_Y + 17);
  tft.println("Scan Crop");
}

bool touchInsideButton(int16_t x, int16_t y) {
  return (x >= BTN_X && x <= BTN_X + BTN_W && y >= BTN_Y && y <= BTN_Y + BTN_H);
}

void drawIdleScreen() {
  tft.fillScreen(COLOR_BG);
  tft.setTextColor(COLOR_TEXT);
  tft.setTextSize(2);
  tft.setCursor(10, 20);
  tft.println("Crop Sentinel AI");

  tft.setTextSize(1);
  tft.setCursor(10, 50);
  tft.println("Field Health: 92% - Healthy");
  tft.setCursor(10, 65);
  tft.setTextColor(COLOR_MUTED);
  tft.println("(placeholder -- real trend calc is Phase 7)");
  tft.setTextColor(COLOR_TEXT);

  tft.setCursor(10, 85);
  char zoneCountMsg[40];
  snprintf(zoneCountMsg, sizeof(zoneCountMsg), "Zones tracked this session: %d", zoneCount);
  tft.setTextColor(COLOR_MUTED);
  tft.println(zoneCountMsg);
  tft.setTextColor(COLOR_TEXT);

  drawScanButton();
}

void drawScanningScreen(const char *zoneId) {
  tft.fillScreen(COLOR_BG);
  tft.setTextColor(COLOR_TEXT);
  tft.setTextSize(2);
  tft.setCursor(10, 20);
  tft.print("Scanning Zone ");
  tft.println(zoneId);
  tft.setTextSize(1);
  tft.setTextColor(COLOR_MUTED);
  tft.setCursor(10, 50);
  tft.println("Waiting for ESP32-S3-CAM...");
  tft.setTextColor(COLOR_TEXT);
}

// ---------------------------------------------------------------------
// Streaming parser for the ESP32's fixed-format JSON reply -- replaces an
// earlier version that buffered the WHOLE line (up to 420 bytes) before
// parsing it. That buffer was a major contributor to this sketch blowing
// its 2KB RAM budget. Since the ESP32 always sends fields in the exact
// same order --
//   {"class":"...","confidence":0.NN,"feat":[n,n,...,n]}\n
// -- there's no need to hold the whole line in memory at once. This reads
// and consumes it directly off the wire, field by field, using only a few
// bytes of scratch space at a time (a numeric accumulator, max ~4 bytes),
// regardless of how long the class name or feat array is.
// ---------------------------------------------------------------------

// Reads chars into outBuf until `terminator` is seen (which is consumed
// but not stored) or `deadline` (an absolute millis() value) passes.
// Truncates silently if outBuf fills before the terminator -- fine here
// since ScanResult.className is intentionally shorter than some of the
// real class label strings.
bool readUntilChar(char terminator, char *outBuf, int outBufLen, unsigned long deadline) {
  int idx = 0;
  while ((long)(millis() - deadline) < 0) {
    if (espLink.available()) {
      char c = espLink.read();
      if (c == terminator) {
        if (outBuf && outBufLen > 0) outBuf[idx < outBufLen - 1 ? idx : outBufLen - 1] = '\0';
        return true;
      }
      if (outBuf && idx < outBufLen - 1) outBuf[idx++] = c;
    }
  }
  return false; // timed out
}

// Consumes exactly the given literal string from the wire, character by
// character, verifying each one matches. Used for the fixed JSON
// punctuation/keys we already know are coming.
bool expectLiteral(const char *literal, unsigned long deadline) {
  for (size_t i = 0; literal[i] != '\0'; i++) {
    while (!espLink.available()) {
      if ((long)(millis() - deadline) >= 0) return false;
    }
    if (espLink.read() != literal[i]) return false;
  }
  return true;
}

bool receiveScanResult(ScanResult &out) {
  out.valid = false;
  unsigned long deadline = millis() + 8000UL;

  if (!expectLiteral("{\"class\":\"", deadline)) return false;
  if (!readUntilChar('"', out.className, sizeof(out.className), deadline)) return false;
  if (!expectLiteral("\",\"confidence\":", deadline)) return false;

  char confBuf[8]; // enough for "0.91" etc -- tiny, stack cost is negligible
  if (!readUntilChar(',', confBuf, sizeof(confBuf), deadline)) return false;
  out.confidence = atof(confBuf);

  if (!expectLiteral("\"feat\":[", deadline)) return false;

  for (int i = 0; i < FEAT_LEN; i++) {
    char numBuf[5]; // "255\0" max -- also negligible
    char terminator = (i < FEAT_LEN - 1) ? ',' : ']';
    if (!readUntilChar(terminator, numBuf, sizeof(numBuf), deadline)) return false;
    out.feat[i] = (int16_t)atoi(numBuf);
  }

  expectLiteral("}", deadline); // best-effort -- everything we need is already parsed either way

  out.valid = true;
  return true;
}

// Phase 4: real fixed-point logistic regression, trained via
// train_tiny_model.py and exported to tiny_model.h. Replaces the earlier
// mean-threshold stub now that a real model exists.
//
// score_fixed = bias + sum(weight[i] * feature[i])   -- integer math only
// class = "diseased" if (score_fixed / MODEL_SCALE) > 0 else "healthy"
//   (valid because logistic regression's decision boundary is exactly
//    intercept + sum(coef*x) == 0 -- sign alone gives the class)
#if FEATURE_COUNT != FEAT_LEN
#error "tiny_model.h's FEATURE_COUNT does not match this sketch's FEAT_LEN -- retrain or fix GRID_SIZE mismatch before flashing."
#endif

bool tinyModelVerdict(const int16_t *feat, int len) {
  int32_t acc = MODEL_BIAS;
  for (int i = 0; i < len; i++) {
    int16_t w = (int16_t)pgm_read_word(&MODEL_WEIGHTS[i]); // PROGMEM read, not plain indexing
    acc += (int32_t)w * (int32_t)feat[i];
  }
  float score = (float)acc / (float)MODEL_SCALE;
  return score > 0.0f; // true = diseased
}

void drawResultScreen(const ScanResult &r, const char *zoneId) {
  tft.fillScreen(COLOR_BG);

  bool primaryDiseased = (strcmp(r.className, "healthy") != 0);
  bool secondaryDiseased = tinyModelVerdict(r.feat, FEAT_LEN);
  bool agree = (primaryDiseased == secondaryDiseased);

  uint16_t headlineColor = primaryDiseased ? COLOR_DISEASED : COLOR_HEALTHY;

  tft.setTextColor(headlineColor);
  tft.setTextSize(2);
  tft.setCursor(10, 15);
  tft.println(primaryDiseased ? r.className : "Healthy");

  tft.setTextColor(COLOR_TEXT);
  tft.setTextSize(1);
  tft.setCursor(10, 45);
  tft.print("Confidence: ");
  tft.print(r.confidence * 100.0f, 1);
  tft.println("%");

  tft.setCursor(10, 60);
  tft.print("Zone: ");
  tft.println(zoneId);

  tft.setCursor(10, 78);
  tft.setTextColor(agree ? COLOR_HEALTHY : ILI9341_YELLOW);
  tft.print("On-Arduino verified: ");
  tft.println(agree ? "OK (agree)" : "MISMATCH -- rescan");
  tft.setTextColor(COLOR_TEXT);

  // Quick prior-reading hint for this zone, ahead of the full Phase 7 trend
  // graph -- only shows if there's at least one earlier reading stored.
  ScanRecord prev;
  tft.setCursor(10, 96);
  if (getPreviousReading(zoneId, prev)) {
    tft.setTextColor(COLOR_MUTED);
    tft.print("Previous reading: ");
    tft.print(prev.confidence * 100.0f, 1);
    tft.print("% (");
    tft.print(prev.classNameTrunc);
    tft.println(")");
  } else {
    tft.setTextColor(COLOR_MUTED);
    tft.println("First reading for this zone -- no history yet.");
  }
  tft.setTextColor(COLOR_TEXT);

  tft.setCursor(10, 114);
  tft.setTextColor(COLOR_MUTED);
  tft.println("(secondary verdict: on-Arduino TinyML model)");
  tft.setTextColor(COLOR_TEXT);

  tft.setCursor(10, 280);
  tft.setTextColor(COLOR_MUTED);
  tft.println("Tap anywhere to return to idle screen");
}

// ---------------------------------------------------------------------
// Dashboard protocol (over the Uno's existing USB Serial link -- NOT
// espLink, which is the separate SoftwareSerial link to the ESP32-S3-CAM).
// Added because the physical touchscreen is currently non-functional and
// there is no other way to trigger a scan or see a result. See
// WEB_DASHBOARD.md for the PC-side design this feeds.
//
// Outbound, printed once per successfully-parsed scan:
//   DASH:{"zone":"B4","class":"...","confidence":0.91,"tinyVerdict":"healthy","agree":true,"ts":123456}
// Inbound, checked every loop() alongside touch:
//   DASH_SCAN:B4\n   -- triggers a scan of zone B4 exactly as if tapped
//                       on the (currently broken) zone-pick grid.
// ---------------------------------------------------------------------

void emitDashLine(const char *zoneId, const ScanResult &r, bool tinyDiseased, bool agree) {
  Serial.print("DASH:{\"zone\":\"");
  Serial.print(zoneId);
  Serial.print("\",\"class\":\"");
  Serial.print(r.className);
  Serial.print("\",\"confidence\":");
  Serial.print(r.confidence, 2);
  Serial.print(",\"tinyVerdict\":\"");
  Serial.print(tinyDiseased ? "diseased" : "healthy");
  Serial.print("\",\"agree\":");
  Serial.print(agree ? "true" : "false");
  Serial.print(",\"ts\":");
  Serial.print(millis());
  Serial.println("}");
}

// Checks the USB Serial link for a "DASH_SCAN:<zoneId>" command. Returns
// true and fills outZoneId if one was received. Non-blocking -- call once
// per loop() iteration.
bool readDashScanCommand(char *outZoneId) {
  static char buf[16];
  static size_t len = 0;

  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n') {
      buf[len] = '\0';
      len = 0;
      const char *prefix = "DASH_SCAN:";
      if (strncmp(buf, prefix, strlen(prefix)) == 0) {
        const char *zonePart = buf + strlen(prefix);
        strncpy(outZoneId, zonePart, 3);
        outZoneId[3] = '\0';
        // Trim any trailing \r from CRLF-sending terminals.
        for (int i = 0; i < 4; i++) if (outZoneId[i] == '\r') outZoneId[i] = '\0';
        return true;
      }
      return false; // some other line -- ignore, not a DASH_SCAN command
    }
    if (len < sizeof(buf) - 1) {
      buf[len++] = c;
    } else {
      len = 0; // overflow guard
    }
  }
  return false;
}

void doScanFlow(const char *zoneId) {
  currentScreen = SCREEN_SCANNING;
  drawScanningScreen(zoneId);

  while (espLink.available()) espLink.read();

  espLink.print("SCAN\n");
  Serial.print("[TX -> ESP32] SCAN  (zone ");
  Serial.print(zoneId);
  Serial.println(")");

  ScanResult result;
  bool gotResult = receiveScanResult(result);

  if (!gotResult) {
    tft.fillScreen(COLOR_BG);
    tft.setTextColor(COLOR_DISEASED);
    tft.setTextSize(2);
    tft.setCursor(10, 20);
    tft.println("Scan failed");
    tft.setTextSize(1);
    tft.setTextColor(COLOR_MUTED);
    tft.setCursor(10, 50);
    tft.println("No/bad reply from ESP32-S3-CAM. Check UART wiring (D2/D3, GND).");
    tft.setCursor(10, 280);
    tft.println("Tap anywhere to return to idle screen");
    currentScreen = SCREEN_RESULT;
    return;
  }

  Serial.print("[RX <- ESP32] class=");
  Serial.print(result.className);
  Serial.print(" confidence=");
  Serial.println(result.confidence, 2);

  // Only store valid, successfully-parsed readings.
  addScanToHistory(zoneId, result.className, result.confidence);
  printZoneHistory(zoneId); // acceptance-test verification output

  bool primaryDiseased = (strcmp(result.className, "healthy") != 0);
  bool tinyDiseased = tinyModelVerdict(result.feat, FEAT_LEN);
  emitDashLine(zoneId, result, tinyDiseased, primaryDiseased == tinyDiseased);


  drawResultScreen(result, zoneId);
  currentScreen = SCREEN_RESULT;
}

void setup() {
  Serial.begin(115200);
  delay(200);
  Serial.println("=== Crop Sentinel AI -- Phase 6: zone tagging + history ===");

  espLink.begin(ESP_BAUD);

  tft.begin();
  tft.setRotation(0);

  touch.begin();
  touch.setRotation(tft.getRotation());

  drawIdleScreen();
  Serial.println("[OK] Idle screen drawn. Tap 'Scan Crop' to tag a zone and start a scan.");
}

void loop() {
  // Remote trigger from the web dashboard -- works even with the
  // touchscreen non-functional. Checked every iteration, independent of
  // touch state, except while a scan is already in progress.
  if (currentScreen != SCREEN_SCANNING) {
    char remoteZoneId[4];
    if (readDashScanCommand(remoteZoneId)) {
      strncpy(currentZoneId, remoteZoneId, sizeof(currentZoneId));
      Serial.print("[DASH] Remote scan trigger for zone ");
      Serial.println(currentZoneId);
      doScanFlow(currentZoneId);
    }
  }

  if (touch.tirqTouched() && touch.touched()) {
    TS_Point p = touch.getPoint();
    int16_t x = map(p.x, TS_MINX, TS_MAXX, 0, tft.width());
    int16_t y = map(p.y, TS_MINY, TS_MAXY, 0, tft.height());

    if (currentScreen == SCREEN_IDLE) {
      if (touchInsideButton(x, y)) {
        currentScreen = SCREEN_ZONE_PICK;
        drawZonePickScreen();
      }
    } else if (currentScreen == SCREEN_ZONE_PICK) {
      char zoneId[4];
      if (zonePickTouchHit(x, y, zoneId)) {
        strncpy(currentZoneId, zoneId, sizeof(currentZoneId));
        doScanFlow(currentZoneId);
      }
    } else if (currentScreen == SCREEN_RESULT) {
      delay(150); // crude debounce
      currentScreen = SCREEN_IDLE;
      drawIdleScreen();
    }
    // SCREEN_SCANNING ignores touch -- doScanFlow() blocks until reply/timeout.
  }
}
